spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: 'jdbc:log4jdbc:h2:mem:test'   # H2 DB 연결 주소 (In-Memory Mode)
    # url: 'jdbc:h2:~/test'   # H2 DB 연결 주소 (Embedded Mode)
    username: security        # H2 DB 접속 ID (사용자 지정)
    password: admin123        # H2 DB 접속 PW (사용자 지정)
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

  logging:  # logging slf4j
    config: classpath:log4j2/log4j2-local.yaml    # default Logging 프레임워크 설정 파일을 참조
#    config: classpath:log4j2/log4j2-local.xml    # default Logging 프레임워크 설정 파일을 참조